### ISSUE TITLE
Discuss: Without deleting the executionClaimHash before executing the action call @ Core, would we have any re-entrancy protection?

### ISSUE THREAD

**Issue by hilmarx** [gelatodigital/gelato-dutchX#117]

**Comment by hilmarx** [comment]
**Update:** I think re-entrancy is actually not an issue any more, because we are not using ```transfer()``` anymore, hence the functions flow control is only passed to triggers and actions, which need to be whitelisted by aggregators anyway. 

Still, I think it would be interesting to know if we have any reentrancy protection except the ```delete``` operation in the ```execute()``` function

**Comment by gitpusha** [comment]
The first `re-entrancy` vector inside the `execute()` fn is our call to `canExecute()` since here we call `trigger.staticcall(_triggerPayload)`. Here we have not `delete` anything yet, so maybe there is a potential for malicious `re-entering` from `malicious trigger` and `triggerPayload`.  A potential scenario: `malicious trigger and payload` get called via `canExecute()`'s `trigger.staticcall` do something on `trigger` and then `re-enter` and proceed to `safeExecute()`'s `action.call` and also do something malicious there. The protection I see immediately here is that we perform a `staticcall` on the `trigger` i.e. `no state changes inside the trigger`. Still worth assessing in more detail.


 The second `re-entrancy` vector is inside the `safeExecute()` fn where we have an external interaction via `_action.call(actionPayload)`. Here, if the `action` and `payload` is a contract function written to `re-enter` into `gelatoCore`'s `execute()` fn, then we have a `re-entrancy` case. However, since we `delete hashedExecutionClaims[_executionClaimId]` BEFORE calling `_action.call(actionPayload)`, the `reentrant` would already fail inside the `canExecute()` fn where we perform the `hash compare` check BEFORE `trigger.staticcall`.

**Comment by gitpusha** [comment]
Closing this issue as we use `nonReentrant` modifier anyway
